### PR TITLE
Support generic collection type for ClumpSource get multiple

### PR DESCRIPTION
**Pull request by williamboxhall**
@fwbrasil

### CODE REVIEW

**Comment by stevenheidel** [comment]
How does this interact with Clump.sourceZip? Obviously it doesn't make sense to have sets there.

**Comment by williamboxhall** [comment]
> How does this interact with Clump.sourceZip? Obviously it doesn't make sense to have sets there.

It will work fine with `Clump.sourceZip` because the `zip` aspect is something we use to wrangle the underlying repository into a form we can build key-value pairs out of. This generic collection is at a much higher abstraction and just effectively represents a convenience way to a developer being able to choose a collection type they wish to use to lookup multiple keys in the underlying `Map[K,Future[V]]`. ClumpFetcher will still use a list to call the repository under the hood and then use the zip function to match the result with the input list it used. Hope that made sense

**Comment by williamboxhall** [comment]
So `clumpSource.get(Set(1,2))` would effectively call (say) `clumpSource.get(2)` then  `clumpSource.get(1)`. Then under the hood `ClumpFetcher` would call the underlying function `fetch(List(2,1))` then the results of that fetch would be zipped back with the input list, a bit like `futureResult.map(listResult => listInputs.zip(listResult)`

**Comment by williamboxhall** [comment]
Also the cool thing is it will still honour call order, so if you have:

```scala
def fetch(keys: List[Key]): Future[List[Value]]
val source = Clump.sourceZip(fetch _)
val result = source.get(Seq(1,2,3))
```
then it will honour the call order under the hood, calling `fetch(List(1,2,3))`

**Comment by stevenheidel** [comment]
That's pretty cool! Thanks for the explanation.

**Comment by fwbrasil** [comment]
:+1:

**Pull request merged**
